spring:
  application:
    name: notification-service

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: 9762b503b72768
    password: ed8de7ca1b356f
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.jobflow.notificationservice.event.ApplicationCreatedEvent

server:
  port: 8081
