spring:
  application:
    name: jobflow-job-service

  datasource:
    url: jdbc:postgresql://localhost:5432/jobflow
    username: jobflow
    password: jobflow

  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers: localhost:9092

  elasticsearch:
    uris: http://localhost:9200

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

server:
  port: 8080